application.name=@project.artifactId@
version=@project.version@
build.revision=@git.commit.id.abbrev@
build.number=@git.commit.id@
build.branch=@git.branch@
build.time=@git.commit.time@
#build.profile=@spring.profiles.active@
