# .github/workflows/javadoc.yml
name: Build Javadoc

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Generate Javadoc
      # Force la locale en anglais pour l'interface Javadoc
      # Utiliser javadoc:aggregate au lieu de javadoc:javadoc si le projet est multi-modules
      run: mvn -B javadoc:javadoc -Duser.language=en --file pom.xml
